In [2]:
import pandas as pd

df = pd.read_csv('./data_dict.csv')

In [3]:
df

,integrator,tstep,param,pos,vel,mass,acc,Etot
0,Euler_base,1,0,[[ 0. -0.51639778 0. ]\n [ 2. ...,[[ 0.25 -0.51639778 0. ]\n [-0.5...,[2. 1.],[[ 0.25 0. 0. ]\n [-0.5 0. 0. ]],0.196931
1,Euler_base,1,1,[[ 0.25 -1.03279556 0. ]\n [ 1.5...,[[ 0.37352647 -0.42071458 0. ]\n [-0.7...,[2. 1.],[[ 0.12352647 0.09568319 0. ]\n [-0.2...,0.350951
2,Euler_base,1,2,[[ 0.62352647 -1.45351014 0. ]\n [ 0.7...,[[ 0.40704367 -0.33763518 0. ]\n [-0.8...,[2. 1.],[[ 0.0335172 0.08307941 0. ]\n [-0.0...,0.380588
3,Euler_base,1,3,[[ 1.03057014 -1.79114532 0. ]\n [-0.0...,[[ 0.40860255 -0.2851124 0. ]\n [-0.8...,[2. 1.],[[ 0.00155888 0.05252278 0. ]\n [-0.0...,0.379986
4,Euler_base,1,4,[[ 1.43917269 -2.07625772 0. ]\n [-0.8...,[[ 0.40198036 -0.25251775 0. ]\n [-0.8...,[2. 1.],[[-0.00662219 0.03259465 0. ]\n [ 0.0...,0.375125
...,...,...,...,...,...,...,...,...
2025,RK4,1,401,[[ 635.2929942 -300.79164295 0. ...,[[ 0.31182859 -0.14675313 0. ]\n [-0.6...,[2. 1.],[[-2.03766362e-07 9.65787805e-08 0.00000000e...,0.355371
2026,RK4,1,402,[[ 635.60482268 -300.93839604 0. ...,[[ 0.31182838 -0.14675304 0. ]\n [-0.6...,[2. 1.],[[-2.03566557e-07 9.64837454e-08 0.00000000e...,0.355371
2027,RK4,1,403,[[ 635.91665096 -301.08514903 0. ...,[[ 0.31182818 -0.14675294 0. ]\n [-0.6...,[2. 1.],[[-2.03367051e-07 9.63888453e-08 0.00000000e...,0.355371
2028,RK4,1,404,[[ 636.22847904 -301.23190192 0. ...,[[ 0.31182798 -0.14675284 0. ]\n [-0.6...,[2. 1.],[[-2.03167815e-07 9.62940803e-08 0.00000000e...,0.355371
2029,RK4,1,405,[[ 636.54030692 -301.37865471 0. ...,[[ 0.31182777 -0.14675275 0. ]\n [-0.6...,[2. 1.],[[-2.02968934e-07 9.61994857e-08 0.00000000e...,0.355371

In [8]:
a = df['pos'].to_list()

In [10]:
import numpy as np
b=np.array(a)

In [11]:
b

array(['[[ 0.         -0.51639778  0.        ]\n [ 2.          1.03279556  0.        ]]',
       '[[ 0.25       -1.03279556  0.        ]\n [ 1.5         2.06559112  0.        ]]',
       '[[ 0.62352647 -1.45351014  0.        ]\n [ 0.75294706  2.90702029  0.        ]]',
       ...,
       '[[  635.91665096  -301.08514903     0.        ]\n [-1269.83330193   602.17029805     0.        ]]',
       '[[  636.22847904  -301.23190192     0.        ]\n [-1270.45695809   602.46380384     0.        ]]',
       '[[  636.54030692  -301.37865471     0.        ]\n [-1271.08061384   602.75730943     0.        ]]'],
      dtype='<U96')